### ISSUE TITLE
 Error in eval(expr, envir, enclos) : object 'datafile' not found 

### ISSUE THREAD

**Issue by minisciencegirl** [briandconnelly/growthcurve#1] opened 2016-03-30 18:06 UTC
# function

fit_curve <- function(d) {
  fit <- fit_growth_logistic(d, time, OD600)
  if (is.na(fit$integral)) {
    data.frame(MaxGrowth = NA,
               MaxRate = NA,
               LagLength = NA)
  }
  else{
    data.frame(MaxGrowth = fit$max_growth[["Estimate"]],
               MaxRate = fit$max_rate[["Estimate"]],
               LagLength = fit$lag_length[["Estimate"]])
  }
}
# growth curve

growthfit <- Bcc1_12_names %>% 
  filter(!grepl("blank", annotation)) %>% #filter out the blank wells
  arrange(annotation, well_alias) %>% 
  group_by(annotation, well_alias) %>%         # Group the data by well and strain annotation
  do(fit_curve(.))                    # For each well, fit a growth curve

[growthcurve_test.xlsx](https://github.com/briandconnelly/growthcurve/files/196132/growthcurve_test.xlsx)

**Comment by briandconnelly** [comment] 2016-03-30 18:19
Huh, I'm getting that error too. I'll see if I can figure it out!

**Comment by minisciencegirl** [comment] 2016-03-30 18:21
Cool thanks.

FYI, I kept annotation, well_alias as factors. time and OD600 as numeric.

**Comment by briandconnelly** [comment] 2016-03-30 18:44
That was tricky (and definitely my fault)!

The problem is with the time column's name---it was trying to call the `time` function.

I'm going to have to figure out how to fix that. For now, you can get things working by renaming it in the data (see the added `select` line):

``` r
growthfit <- Bcc1_12_names %>% 
    select(well_alias, annotation, Time=time, OD600) %>%
    filter(!grepl("blank", annotation)) %>% #filter out the blank wells
    arrange(annotation, well_alias) %>% 
    group_by(annotation, well_alias) %>% # Group the data by well and strain annotation
    do(fit_curve(.)) # For each well, fit a growth curve
```

and in `fit_curve`:

``` r
fit_curve <- function(d) {
    fit <- fit_growth_logistic(d, Time, OD600)

    if (is.na(fit$integral)) {
        data.frame(MaxGrowth = NA,
                   MaxRate = NA,
                   LagLength = NA)
    }
    else{
        data.frame(MaxGrowth = fit$max_growth[["Estimate"]],
                   MaxRate = fit$max_rate[["Estimate"]],
                   LagLength = fit$lag_length[["Estimate"]])
    }
}
```

**Comment by minisciencegirl** [comment] 2016-03-30 19:04
Thank you so much for your help!! :-)

By the way, I noticed that one of the required package for installing growthcurve is pander..

**Comment by briandconnelly** [comment] 2016-03-30 19:56
Thanks, that's a good catch! pander's in the vignette, but probably isn't needed anymore.

If you want to trim down your code, you don't need functions like `fit_curve` with the version I just checked in. Instead:

``` r
growthfit <- Bcc1_12_names %>% 
    select(well_alias, annotation, Time=time, OD600) %>%
    filter(!grepl("blank", annotation)) %>% #filter out the blank wells
    arrange(annotation, well_alias) %>% 
    group_by(annotation, well_alias) %>% # Group the data by well and strain annotation
    do(as.data.frame(fit_growth_logistic(., Time, OD600))
```

**Comment by minisciencegirl** [comment] 2016-03-30 20:27
Thanks!! :thumbsup:

**Closed as completed** 2016-03-30 20:26 UTC
